### ISSUE TITLE
Delete user fails

### ISSUE THREAD

**Issue by RhysLees** [codebar-ag/laravel-zammad#32]
<img width="712" alt="image" src="https://github.com/codebar-ag/laravel-zammad/assets/43909932/e04e629b-cb4b-4e42-ab95-82da76d67cd4">

<img width="1030" alt="image" src="https://github.com/codebar-ag/laravel-zammad/assets/43909932/f5c92404-b059-4ec9-bc08-35099a7b9ab0">

**Comment by StanBarrows** [comment]
@RhysLees Delete all existing users first.
